sudo: false

language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - "pip install flake8"

becore_script: "flake8 plaid tests"
script: nosetests
